[package]
name = "hoist"
version = "0.1.0"
authors = ["Sebastian Berglönn <sebastianberglonn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bollard = "0.8"
actix-web = "3"